---
name: main - buildtest for manual test or when PR


on:
  workflow_dispatch:
  pull_request: 
    types: opened
    branches: 
      - master
  push:
    branches:
      - dev


jobs:
  ##############################################
  #
  # Build udp-broadcast-relay-redux software for multiple arch
  #
  build_and_upload_matrix:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest

  ##############################################
  #
  # Build container
  #
  build_container_matrix:
    needs: build_and_upload_matrix
    uses: ./.github/workflows/reuseable_build_container.yml
    secrets: inherit
    with:
      artifact-name: buildtest
      registry_image: hasechris92/udp-broadcast-relay

  ##############################################
  #
  # get all container images, merge and push
  #
  merge_tags:
    needs: build_container_matrix
    uses: ./.github/workflows/reuseable_merge_tags.yml
    secrets: inherit
    with:
      artifact-name: buildtest
      registry_image: hasechris92/udp-broadcast-relay



...