---
name: main - Release new version of container (run from schedule or from PR close on merge)


on:
  pull_request: 
    types: closed
    branches: 
      - master

jobs:
  ##############################################
  #
  # Build udp-broadcast-relay-redux software for multiple arch
  #
  build_and_upload_matrix:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: release

  ##############################################
  #
  # Build container
  #
  build_container_matrix:
    needs: build_and_upload_matrix
    uses: ./.github/workflows/reuseable_build_container.yml
    secrets: inherit
    with:
      artifact-name: release
      registry_image: hasechris92/udp-broadcast-relay

  ##############################################
  #
  # get all container images, merge and push
  #
  merge_tags:
    needs: build_container_matrix
    uses: ./.github/workflows/reuseable_merge_tags.yml
    secrets: inherit
    with:
      artifact-name: $GITHUB_RUN_NUMBER
      digest-name: release
      registry_image: hasechris92/udp-broadcast-relay


...