---
name: main - buildtest for manual test or when PR


on:
  workflow_dispatch:
  pull_request: 
    types: opened
    branches: 
      - main
  push:
    branches:
      - dev

jobs:
  filechange_detection:
    uses: ./.github/workflows/reuseable_filechange_detection.yml
  build_and_upload:
    if: needs.filechange_detection.changes_found_source == 'true' || needs.filechange_detection.changes_found_build_software == 'true' || needs.filechange_detection.changes_found_build_buildtest == 'true'
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      buildarch_zig: "x86_64"
      zigversion: 0.11.0
  build_container:
    needs: build_and_upload
    if: needs.filechange_detection.changes_found_source == 'true' || needs.filechange_detection.changes_found_build_software == 'true' || needs.filechange_detection.changes_found_build_container == 'true' || needs.filechange_detection.changes_found_build_buildtest == 'true'
    uses: ./.github/workflows/reuseable_build_container.yml
    secrets: inherit
    with:
      artifact-name: buildtest
      dumb-init-version: 1.2.5
      buildarch_zig: "x86_64"
      buildarch_buildx: "amd64"

...