---
name: main - buildtest for manual test or when PR


on:
  workflow_dispatch:
  pull_request: 
    types: opened
    branches: 
      - main
  push:
    branches:
      - dev


jobs:
  ##############################################
  #
  # Build udp-broadcast-relay-redux software for multiple arch
  #
  build_and_upload_amd64:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "x86_64"
      zig_buildos: "linux"
      zig_buildlibc: "musl"
      zig_version: 0.11.0

  build_and_upload_x86:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "x86"
      zig_buildos: "linux"
      zig_buildlibc: "musl"
      zig_version: 0.11.0

  build_and_upload_raspi1_raspicm1_raspizero1:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "arm"
      zig_buildos: "linux"
      zig_buildlibc: "musleabihf"
      zig_buildcpu: "-mcpu=arm1176jzf_s"
      zig_version: 0.11.0

  build_and_upload_raspi2:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "arm"
      zig_buildos: "linux"
      zig_buildlibc: "musleabihf"
      zig_buildcpu: "-mcpu=cortex_a7"
      zig_version: 0.11.0

  build_and_upload_raspi2v12_raspi3_raspizero2w_32bit:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "arm"
      zig_buildos: "linux"
      zig_buildlibc: "musleabihf"
      zig_buildcpu: "-mcpu=cortex_a53"
      zig_version: 0.11.0

  build_and_upload_raspi2v12_raspi3_raspizero2w_64bit:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "aarch64"
      zig_buildos: "linux"
      zig_buildlibc: "musl"
      zig_buildcpu: "-mcpu=cortex_a53"
      zig_version: 0.11.0

  build_and_upload_raspi4_raspicm4_rpi400:
    uses: ./.github/workflows/reuseable_build_and_upload.yml
    with:
      artifact-name: buildtest
      zig_buildarch: "aarch64"
      zig_buildos: "linux"
      zig_buildlibc: "musl"
      zig_buildcpu: "-mcpu=cortex_a72"
      zig_version: 0.11.0

  ##############################################
  #
  # Build container
  #
  build_container_amd64:
    needs: build_and_upload_amd64
    uses: ./.github/workflows/reuseable_build_container.yml
    secrets: inherit
    with:
      artifact-name: buildtest
      dumb-init-version: 1.2.5
      buildarch_zig: "x86_64"
      buildarch_buildx: "amd64"

  build_container_x86:
    needs: build_and_upload_x86
    uses: ./.github/workflows/reuseable_build_container.yml
    secrets: inherit
    with:
      artifact-name: buildtest
      dumb-init-version: 1.2.5
      buildarch_zig: "x86_64"
      buildarch_buildx: "amd64"











...