---
name: reuseable - check changes in repo

on:
  workflow_call:

jobs:
  filechange_detection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changes_found_source: ${{ steps.filter.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src: 
              - 'main.c'