---
name: reuseable - check changes in repo

on:
  workflow_call:

jobs:
  filechange_detection:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    outputs:
      changes_found_source: ${{ steps.filter.outputs.src }}
      changes_found_workflow_build_software: ${{ steps.filter.outputs.workflow_build_software }}
      changes_found_workflow_build_container: ${{ steps.filter.outputs.workflow_build_container }}
      changes_found_workflow_build_buildtest: ${{ steps.filter.outputs.workflow_buildtest }}
    steps:
      - run: apk add --no-cache git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: ls -la
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src: 
              - 'main.c'
            workflow_build_software:
              - '.github/workflows/reuseable_build_and_upload.yml'
            workflow_build_container:
              - '.github/workflows/reuseable_build_container.yml'
            workflow_buildtest:
              - '.github/workflows/main_buildtest.yml'