---
name: reuseable - build and upload

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      zig_buildarch:
        required: true
        type: string
      zig_buildos:
        required: true
        type: string
      zig_buildlibc:
        required: true
        type: string
      zig_buildcpu:
        required: false
        type: string
      zig_version:
        required: true
        type: string

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ inputs.zig_version }}
      - name: Compile udp-broadcast-relay-redux with Zig Compiler
        run: zig build-exe -target ${{ inputs.zig_buildarch }}-${{ inputs.zig_buildos }}-${{ inputs.zig_buildlibc }} ${{ inputs.zig_buildcpu }} -lc -O ReleaseSmall --name udp-broadcast-relay-redux main.c
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}-${{ inputs.zig_buildarch }}-${{ inputs.zig_buildos }}-${{ inputs.zig_buildlibc }}${{ '-' + inputs.zig_buildcpu }}
          path: udp-broadcast-relay-redux
  
...