---
name: reuseable - build container

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      dumb-init-version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'Yelp/dumb-init'
          version: '${{ inputs.dumb-init-version }}'
          file: '${{ buildarch }}'
      - run: ls -la
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udp-broadcast-relay:${{ inputs.artifact-name }}
          context: .
          file: Dockerfile.${{ inputs.artifact-name }}

...