---
name: reuseable - build container

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      buildx_buildarch:
        required: true
        type: string
      zig_buildarch:
        required: true
        type: string
      zig_buildos:
        required: true
        type: string
      zig_buildlibc:
        required: true
        type: string
      zig_buildcpu:
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}-${{ inputs.zig_buildarch }}-${{ inputs.zig_buildos }}-${{ inputs.zig_buildlibc }}-${{ inputs.zig_buildcpu }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/udp-broadcast-relay:${{ inputs.artifact-name }}
          context: .
          file: Dockerfile.${{ inputs.artifact-name }}
          platforms: ${{ inputs.zig_buildos }}/${{ inputs.buildx_buildarch }}


...